### ISSUE TITLE
there is no ss_dota_obb.py  in ../_base_/datasets/

### ISSUE THREAD

**Issue by 1994su** [jbwang1997/OBBDetection#1]
there is no ss_dota_obb.py  in ../_base_/datasets/

**Comment by jbwang1997** [comment]
ss_dota_obb.py is in /OBBDetection/configs/obb/_base_/datasets.
The _base_ path in the config should be changed relatively to your config path.

**Comment by jbwang1997** [comment]
ss_dota_obb.py is in /OBBDetection/configs/obb/_base_/datasets.
The _base_ path in the config should be changed relatively to your config path.

**Comment by jbwang1997** [comment]
Is there any error message when running the program?

**Comment by 1994su** [comment]
你好，有一些问题需要请教？有其他联系方式吗？还麻烦知道一下。

发自我的iPhone


------------------ Original ------------------
From: jbwang1997 ***@***.***&gt;
Date: Tue,Jul 13,2021 4:06 PM
To: jbwang1997/OBBDetection ***@***.***&gt;
Cc: 1994su ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [jbwang1997/OBBDetection] there is no ss_dota_obb.py  in ../_base_/datasets/ (#1)





 
Is there any error message when running the program?

**Comment by jbwang1997** [comment]
可以微信，我的微信号是jbwang97
