### ISSUE TITLE
About reappearance model

### ISSUE THREAD

**Issue by Xuyihaoby** [jbwang1997/OBBDetection#101]
Hello！I was wondering whether the representation of the rotate box is same as the original model,when you reappear the model.And whether the representation has a large impact on the final results.

**Comment by jbwang1997** [comment]
The angle definition in OBBDetection is different from AerialDetection and S2ANet. I let the angle of the rotating box range in [-pi/2, pi/2] for the convenience of angle regression. And the angles are also counterclockwise to fit the roi_align_rotated.

The angle range doesn't have a large impact on results. But some operations like the projection of dx and dy can largely influence the final results. [This repo](https://github.com/SJTU-Thinklab-Det/r3det-pytorch) makes a comparison of different representations.

**Comment by Xuyihaoby** [comment]
> The angle definition in OBBDetection is different from AerialDetection and S2ANet. I let the angle of the rotating box range in [-pi/2, pi/2] for the convenience of angle regression. And the angles are also counterclockwise to fit the roi_align_rotated.
> 
> The angle range doesn't have a large impact on results. But some operations like the projection of dx and dy can largely influence the final results. [This repo](https://github.com/SJTU-Thinklab-Det/r3det-pytorch) makes a comparison of different representations.

Thank you for answering the question!!!! 
The data of [repo](https://github.com/SJTU-Thinklab-Det/r3det-pytorch)  shows that projection is very important.

**Comment by Xuyihaoby** [comment]
Do you mind providing the log of training s2anet？
