### ISSUE TITLE
使用MSRA-TD500进行训练

### ISSUE THREAD

**Issue by juzh1998** [jbwang1997/OBBDetection#109]
您好，我尝试使用MSRA-TD500在Retinanet_r50_fpn模型上进行训练，配置文件由retinanet_r50_fpn_3x_hrsc修改得到，使用的dataloader为您在dataset中预先写好的，最终结果AP50仅为56.58，感觉有点低，请问这个结果是否正常？

**Comment by jbwang1997** [comment]
MSRA-TD500仅有500张图片，需要设置更长的训练周期，可以参考一些论文中的设置重新设置训练参数。

**Comment by juzh1998** [comment]
感谢您的回复，我研究完论文里面的配置之后，发现一方面可能是训练周期的原因，因此我将训练周期从6X提高到了9X，AP50也随之提升到了60，另外一个原因我感觉可能是是论文中使用的retinanet中采用了旋转锚框，但原论文代码是基于tf实现的，不知道您是否有计划在mmdet上实现旋转锚框的计划，或者是否有这方面的资料，如果有的的话，能否麻烦您附一下链接？

**Comment by jbwang1997** [comment]
最近有一些其他的任务，所以旋转锚框的计划可能需要比较晚才开始。
现在使用的Theta0AcnhorGenerator其实已经是旋转的anchor了，只是只有0一种角度，可以参考这个程序进行修改。

**Comment by juzh1998** [comment]
好的，感谢您的答复
