### ISSUE TITLE
FCOS OBB

### ISSUE THREAD

**Issue by czy341181** [jbwang1997/OBBDetection#13]
Could you provide the config of FCOS OBB methods ? I have also implemented a version myself and would like to compare the performance with your implementation. Thanks for your great work

**Comment by jbwang1997** [comment]
Hello. The FCOS OBB is still under development. I will remind you in this issue when it is published.

**Comment by czy341181** [comment]
Thanks!

**Comment by jbwang1997** [comment]
Hello! the FCOS OBB has been published and the results will be right away.
