### ISSUE TITLE
测试的时候进度卡住

### ISSUE THREAD

**Issue by lzj1998** [jbwang1997/OBBDetection#136]
在使用retinanet测试 得到用txt文本表示的结果过程中会卡住
  --format-only --options save_dir=CKPT/retinanet_obb_r50_fpn_1x_dota10/test_result_txt
Use load_from_local loader
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 5297/5297, 15.3 task/s, elapsed: 346s, ETA:     0s
Merging patch bboxes into full image!!!
Multiple processing
[>>>>>>>>>>>>>>>>>>>>>>                            ] 209/458, 12.4 task/s, elapsed: 17s, ETA:    20s

就是卡在209不动了。因为test没有gt。所以我用的val

**Comment by jbwang1997** [comment]
可以换成单进程和图，在命令最后再增加nproc=1

**Comment by qierrrrrrr** [comment]
> 可以换成单进程和图，在命令最后再增加nproc=1

您好，加上命令之后multiple processing确实变成了single processing 但是好像进度条依然卡住不动

**Comment by Panhonganadd** [comment]
修改了之后不会卡住，但是会花五六个小时才能完成。
![image](https://github.com/jbwang1997/OBBDetection/assets/147368008/35ef1cde-4f04-4f26-8c46-b0b47edd2f56)
