### ISSUE TITLE
**Results**

### ISSUE THREAD

**Issue by zjutlouis1011** [jbwang1997/OBBDetection#15]
dota数据集训练完12个epoch后，用demo/test.py 测试了dota的test图片，结果图像中的每个目标都有很多的框，感觉不是最终的检测结果，想问一下这是为什么
图片如下：
https://gitee.com/young98/cloudimg/raw/master/img/image-20210901114455807.png
https://gitee.com/young98/cloudimg/raw/master/img/image-20210901114442680.png

**Comment by jbwang1997** [comment]
这有可能是训练的是[orpn_r50_fpn_1x_dota10.py](https://github.com/jbwang1997/OBBDetection/blob/master/configs/obb/oriented_rcnn/orpn_r50_fpn_1x_dota10.py)，这个confgi只是orpn，输出的结果是有向的proposals.

完整的oriented_rcnn需要训练[faster_rcnn_orpn_r50_fpn_1x_dota10.py](https://github.com/jbwang1997/OBBDetection/blob/master/configs/obb/oriented_rcnn/faster_rcnn_orpn_r50_fpn_1x_dota10.py)

**Comment by zjutlouis1011** [comment]
> 这有可能是训练的是[orpn_r50_fpn_1x_dota10.py](https://github.com/jbwang1997/OBBDetection/blob/master/configs/obb/oriented_rcnn/orpn_r50_fpn_1x_dota10.py)，这个confgi只是orpn，输出的结果是有向的proposals.
> 
> 完整的oriented_rcnn需要训练[faster_rcnn_orpn_r50_fpn_1x_dota10.py](https://github.com/jbwang1997/OBBDetection/blob/master/configs/obb/oriented_rcnn/faster_rcnn_orpn_r50_fpn_1x_dota10.py)
好的谢谢！
