### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by xumengen** [jbwang1997/OBBDetection#16]
![image](https://user-images.githubusercontent.com/38242124/131769029-6b18d1df-ca9c-4d89-8f1a-9bf0f96668ba.png)
![image](https://user-images.githubusercontent.com/38242124/131769042-f39c037b-bcce-4a8d-aff0-a8ce0e331703.png)

pytorch1.2+cuda10.0 编译会报这个错，是什么原因呀

**Comment by jbwang1997** [comment]
比较低的 pytorch 中要将所有cpp与cu文件中的 .data_ptr 要替换成 .data
