### ISSUE TITLE
如何训练自己的数据集？

### ISSUE THREAD

**Issue by hust-lidelong** [jbwang1997/OBBDetection#18]
作者，您好，您的这项工作非常有意义。
我的数据集是通过使用rolabelimg或labelimg2给图片打的标签，请问，如何采用您的code训练自己的数据集，该数据集的特点是：图片尺寸是1280*960，共有37类物体，物体占比较大，不需要对图片进行切割。需要对打标格式进行转化吗，接下来可以做哪些改动，谢谢！

**Comment by jbwang1997** [comment]
如果是新的数据集可以在mmdet/datasets中自己定义新的dataset类并继承mmdet/datasets/custom.py中的CustomDataset。

数据的格式可以参考[这里](https://github.com/jbwang1997/OBBDetection/blob/master/mmdet/datasets/custom.py#L23)。这里的bboxes要是BboxToolkit定义的旋转框格式，格式说明可以见[这里](https://github.com/jbwang1997/BboxToolkit/blob/master/USAGE.md)

**Comment by hust-lidelong** [comment]
> 如果是新的数据集可以在mmdet/datasets中自己定义新的dataset类并继承mmdet/datasets/custom.py中的CustomDataset。
> 
> 数据的格式可以参考[这里](https://github.com/jbwang1997/OBBDetection/blob/master/mmdet/datasets/custom.py#L23)。这里的bboxes要是BboxToolkit定义的旋转框格式，格式说明可以见[这里](https://github.com/jbwang1997/BboxToolkit/blob/master/USAGE.md)

非常感谢您的指点！

**Comment by libingDY** [comment]
您好，能详细介绍下整个流程吗？
