### ISSUE TITLE
rotated ROI while keeping original aspect ratio?

### ISSUE THREAD

**Issue by WeihongM** [jbwang1997/OBBDetection#2]
Does this project support extract rotated RoI(rroi align) while also keeping the aspect ratio?

**Comment by jbwang1997** [comment]
Sorry, we don't have this kind of RRoI Align.

I think one motivation of RoI Align is to make RoI features into a certain dimension, so as to all RoI features can be forward parallelly. So all features outputted by RoI Align should be in the same aspect ratio.
