### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by lijain** [jbwang1997/OBBDetection#20]
安装环境：
 
![714e12759c95269f6e6ae331ec2e29d](https://user-images.githubusercontent.com/18046568/132279175-ff4dd3f4-f3f4-4175-a1f1-079942612439.png)
编译也没有问题，预测却遇到：
![bfc3d2c90ac20c2c83e3a66aa618900](https://user-images.githubusercontent.com/18046568/132279216-15008c02-fac5-40b3-a2c2-97ff529def35.png)
求解：

**Comment by jbwang1997** [comment]
我们提供的模型都是在pytorch1.6的环境下训练的，如果用低版本的pytorch可能无法加载。

可以尝试升级pytorch
