### ISSUE TITLE
输出6个预测值如何转为poly的顶点坐标8个值结果？

### ISSUE THREAD

**Issue by MMountains** [jbwang1997/OBBDetection#21]
尊敬的作者您好，感谢您的代码分享！
在使用的过程中需要将输出结果转化为顶点的8个坐标值，请问输出的6个预测值分别是[center_x, center_y, w, h, theta, confidence]吗？还是说表示其他值？感谢😀

**Comment by jbwang1997** [comment]
六个值的预测就是[center_x, center_y, w, h, theta, confidence]。

如果要转换为8个点的坐标可以先将confidence split下来。tensor使用mmdet.core.bbox2type(bboxes, 'poly'), np.ndarray使用BboxToolkit.bbox2type(bboxes, 'poly')来进行转换

**Comment by MMountains** [comment]
好的，感谢！
