### ISSUE TITLE
如何尺度测试

### ISSUE THREAD

**Issue by wenjuntan** [jbwang1997/OBBDetection#22]
您好，我将test数据集进行了多尺度裁剪，但是合并之后的结果会有一些多余的框，我看到test.py中-options可以设置ign_scale_ranges，跟这个有关吗

**Comment by jbwang1997** [comment]
多尺度测试会比单尺度测试生成更多的检测结果，这个无法避免。可以通过score-thr相对的过滤

ign_scale_range是之前想要在多尺度上实现像SNIP一样的功能，但是还没有测试过效果。
