### ISSUE TITLE
多卡disttest出现报错

### ISSUE THREAD

**Issue by zhaogev5** [jbwang1997/OBBDetection#23]
当我使用多次卡测试时出现了如下报错，请问是什么原因呢
obb_anchor_head.py", line 585, in get_bboxes   
img_shape = img_metas[img_id]['img_shape']
TypeError: 'DataContainer' object is not subscriptable
感谢您

**Comment by jbwang1997** [comment]
这好像是pytorch某一个版本的bug，可以换一下pytorch版本试一下
