### ISSUE TITLE
Samples_per_gpu set to 1 when inference

### ISSUE THREAD

**Issue by YangHai-1218** [jbwang1997/OBBDetection#25]
Hi, thanks for your work!
But I was just wondering why you have to set the samples_per_gpu=1 when inference.
Does there exist some bug? Or some other concern is within it?

**Comment by jbwang1997** [comment]
It's a legacy problem from MMDetection earlier vision. This repo is based on the MMdetection v2.2 where all models' post-processing are written under the condition that batch size is 1.

In higher vision MMDetection, this problem has been fixed.

**Comment by YangHai-1218** [comment]
Thanks! 
But do you have any plan to fix this problem or just update to a higher version MMDetection?

**Comment by jbwang1997** [comment]
I have a plan to update the version of MMDetection, but it's a big project.😖
The update maybe takes a long time.

**Comment by YangHai-1218** [comment]
Thanks! 
It is truly a big project and it is really not easy to fix the problem. 
Anyway, looking forward to the updated version!
