### ISSUE TITLE
--format-only 报错

### ISSUE THREAD

**Issue by printfxs** [jbwang1997/OBBDetection#27]
使用dota1.0跑指标时，输出 “Merging patch bboxes into full image!!! ”后进度条一直为0.

**Comment by jbwang1997** [comment]
可以在测试的时候先使用--show可视化一下检测是否正确，出现这种情况可能是因为模型没有训练好，检测的目标过多，nms速度很慢

**Comment by printfxs** [comment]
![图片](https://user-images.githubusercontent.com/19660166/133886897-d61df534-d068-4bf7-b1e3-d1f3becad4e3.png)
模型我可视化看过了，检测都是正常的。

**Comment by jbwang1997** [comment]
多尺度裁图化，一张图片裁下来的图像块数量可能很多，融合的速度会变慢，这个现在还没有解决的方法。
现在程序应该是在正常运行。

**Comment by printfxs** [comment]
( ▼-▼ )，已经跑了三天了，还是卡在0上。

**Comment by jbwang1997** [comment]
这种情况我还没有遇见过，可以先尝试不使用ms的config跑一下

**Comment by printfxs** [comment]
恩恩，感谢您的回复。这个问题我也会再调试调试。

**Comment by printfxs** [comment]
将track_parallel_progress()替换为track_progress(),单线程执行，一切都正常了。

**Comment by qierrrrrrr** [comment]
> 将track_parallel_progress()替换为track_progress(),单线程执行，一切都正常了。

请问这个函数的参数在哪里修改呢，谢谢
