### ISSUE TITLE
可以提供更多旋转模型的预训练权重吗？

### ISSUE THREAD

**Issue by HsLOL** [jbwang1997/OBBDetection#28]
非常感谢您出色的工作！
我在旋转检测的readme.md中发现，目前只有**gliding_vertex**、**oriented_rcnn**、**retinanet_obb**提供了训练好的权重，想问一下剩下模型训练好的权重什么时候更新呢？

**Comment by jbwang1997** [comment]
训练好的模型在之后将会上传，由于之前疏于整理，一些模型被我删了，之后会重新训练并上传。

**Comment by HsLOL** [comment]
> 训练好的模型在之后将会上传，由于之前疏于整理，一些模型被我删了，之后会重新训练并上传。

好的，非常感谢您的回复！
