### ISSUE TITLE
error:torch1.4.0 is installed but torch==1.3.1 is required by 'torchvision'

### ISSUE THREAD

**Issue by meisun1207** [jbwang1997/OBBDetection#3]
when i build obbdetection, I met the error: error:torch1.4.0 is installed but torch==1.3.1 is required by 'torchvision'.
However  I have installed torchvision==0.4.2 and torch==1.3.1 .
![image](https://user-images.githubusercontent.com/89020440/129563103-39c4f64d-8d85-44cf-9d71-6eef7dfe5eb3.png)

**Comment by jbwang1997** [comment]
It seems there is something wrong with your environment. Please check if the vision of Pytorch is 1.3.1.

I recommend installing Pytorch following the guide of [pytorch install](https://pytorch.org/get-started/previous-versions/)

**Comment by meisun1207** [comment]
> It seems there is something wrong with your environment. Please check if the vision of Pytorch is 1.3.1.
> 
> I recommend installing Pytorch following the guide of [pytorch install](https://pytorch.org/get-started/previous-versions/).

确实是我的环境有问题，之前高版本的torch没有清除干净，还想问下作者使用的是哪个版本的torch，因为我在执行过程中发现使用了torch.square这个函数是torch 1.3.1中所没有的

**Comment by jbwang1997** [comment]
我pytorch版本是1.6.0的。

**Comment by meisun1207** [comment]
> 我pytorch版本是1.6.0的。
感谢，可以成功运行了
