### ISSUE TITLE
训练时不过滤无目标图片

### ISSUE THREAD

**Issue by liliwannian** [jbwang1997/OBBDetection#30]
您好，我想把所有图片放进去训练，就是有目标和没目标都进行训练，请问应该怎么修改？希望您有空能够解答，感谢！

**Comment by jbwang1997** [comment]
在dataset中会将没有目标的图像块过滤，如果要训练没有目标的图像块需要修改dataset的[代码](https://github.com/jbwang1997/OBBDetection/blob/master/mmdet/datasets/obb/dota.py#L56)

之后在pipeline里面也会有FliterEmpty去过滤没有目标的图像块，需要删除掉。

**Comment by liliwannian** [comment]
已成功修改，非常感谢！
