### ISSUE TITLE
在模型转换时，onnx装的是什么版本

### ISSUE THREAD

**Issue by printfxs** [jbwang1997/OBBDetection#31]

**Comment by printfxs** [comment]
RuntimeError: roi_width >= 0 && roi_height >= 0INTERNAL ASSERT FAILED at "/home/workspace/OBBDetection-master/mmdet/ops/roi_align_rotated/src/roi_align_rotated_cpu.cpp":237, please report a bug to PyTorch. ROIs in ROIAlignRotated do not have non-negative size!

我在转换过程中，出现了以上报错。

**Comment by jbwang1997** [comment]
这个功能我还没有用过，这个报错是因为RoIAlign的obb边长小于0了。
