### ISSUE TITLE
可以兼容更强的backbone吗

### ISSUE THREAD

**Issue by czy341181** [jbwang1997/OBBDetection#33]
您好，新版本的mmdetection里发布了swin transformer，但是板本有点高。需要mmcv的板本也很高。 您这里是0.6.2，请问怎么才能在你的code base中加入swin transformer进一步提高精度呢

**Comment by jbwang1997** [comment]
这个还不太好实现，因为新版本的MMDetection中很多文件的位置都发生了变化。

可以尝试将新版的mmcv重命名，让它和mmcv0.6.2能够共存。
