### ISSUE TITLE
关于 编译mmdet 过程产生的问题

### ISSUE THREAD

**Issue by Zhangming001** [jbwang1997/OBBDetection#35]
作者，你好
我的Pytorch版本为1.6.0  ninja 版本为1.10.2
我在编译mmdet的时候会出现下边这个错误
![image](https://user-images.githubusercontent.com/45568217/135192115-ece88f75-4400-45b4-bf6f-89aff123979e.png)
我在网上看到好像是pytorch版本的原因 我降到1.3以后可以编译通过 但是会在加载预训练模型的时候出错。请问一下该怎么解决

**Comment by jbwang1997** [comment]
这是编译哪个文件，现在项目可以在pytorch1.6下编译

**Comment by Zhangming001** [comment]
我执行的是mmdet的安装命令
pip install -v -e .  # or "python setup.py develop"
报错了
但是pytorch1.3可以安装通过

**Comment by Zhangming001** [comment]
> 这是编译哪个文件，现在项目可以在pytorch1.6下编译


我执行的是mmdet的安装命令
pip install -v -e . # or "python setup.py develop"
报错了
但是pytorch1.3可以安装通过

**Comment by Zhangming001** [comment]
> 这是编译哪个文件，现在项目可以在pytorch1.6下编译

我想问问 你使用的gcc和g++ 版本是哪个 以及cuda 版本

**Comment by jbwang1997** [comment]
我的
pytorch1.6 
cuda10.1.243 
gcc g++ 5.4.0

**Comment by Zhangming001** [comment]
> 我的 pytorch1.6 cuda10.1.243 gcc g++ 5.4.0

好的，我去降低一下gcc g++ 版本试试，十分感谢你的回复

**Comment by Zhangming001** [comment]
问题已经解决，是我之前的gcc版本过高导致的。
