### ISSUE TITLE
测试时是否翻转和旋转

### ISSUE THREAD

**Issue by liliwannian** [jbwang1997/OBBDetection#37]
您好，这是我测试时的pipeline
pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipRotateAug',
                img_scale=[(1024, 1024)],
                h_flip=False,
                v_flip=False,
                rotate=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='OBBRandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='RandomOBBRotate', rotate_after_flip=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='OBBCollect', keys=['img'])
                ]
其中h_flip、v_flip、rotate都是false，但是transforms中又有OBBRandomFlip和RandomOBBRotate。请问到底有没有翻转和旋转？希望您能抽空解答，十分感谢！

**Comment by jbwang1997** [comment]
h_flip, vflip, rotate是false是不会进行翻转旋转测试的，其中有OBBRandomFlip与RandomOBBRotate是他们要生成一些数据比如生成results['angle'] = 0等

**Comment by liliwannian** [comment]
好的，谢谢。请问此代码有没有实现测试时翻转旋转操作呢？

**Comment by jbwang1997** [comment]
单阶段网络不支持，双阶段网络是可以的，但是测试结果好像不如不加，翻转与旋转使产生的假正例数量上升，可以尝试一下。

**Comment by liliwannian** [comment]
好的，十分感谢您！
