### ISSUE TITLE
pytorch版本和cuda

### ISSUE THREAD

**Issue by yzk-lab** [jbwang1997/OBBDetection#38]
我在1080上的系统cuda是10.1，我在配置过程中使用了pytorch1.3.1和cudatolkit10.0.130能够通过编译，但是会报出torch没有square属性，是说pytorch版本太低了吗而没有这个属性吗？
后面我尝试着升高版本在另一台3090GPU的服务器上使用cuda11.0+pytorch1.7.1但是此时编译没法通过，具体问题如下，感谢您的帮助，这主要是什么原因呢？有没有什么建议呢？
![`_2EHO`ZVGHZX3}Y4V~4}_M](https://user-images.githubusercontent.com/41197028/135460410-e3031541-fa30-4043-85aa-2ae38a906ef2.png)

**Comment by yzk-lab** [comment]
![1`CD`Z~K1C%S3O$}BEXOLQ7](https://user-images.githubusercontent.com/41197028/135460932-f3ff4b00-a9af-4cce-85da-cc88f07bdf64.png)

**Comment by jbwang1997** [comment]
可以参考一下这个[博客](https://blog.csdn.net/qq_30614451/article/details/111173703)

**Comment by Ryanye2000** [comment]
> ![1CDZ~K1C%S3O$}BEXOLQ7](https://user-images.githubusercontent.com/41197028/135460932-f3ff4b00-a9af-4cce-85da-cc88f07bdf64.png)

兄弟你这个问题解决了吗，我也遇到了

**Comment by yzk-lab** [comment]
应该是cuda版本和pytorch不对应。要对应的版本，我现在使用3090+cuda11.0可以编译通过了。



***@***.***
 
发件人： Ryanye2000
发送时间： 2022-04-01 11:53
收件人： jbwang1997/OBBDetection
抄送： yzk-lab; Author
主题： Re: [jbwang1997/OBBDetection] pytorch版本和cuda (#38)
兄弟你这个问题解决了吗，我也遇到了
―
