### ISSUE TITLE
About iou loss

### ISSUE THREAD

**Issue by ming71** [jbwang1997/OBBDetection#4]
Will you support rotated IoU loss in Oriented RCNN? (I've found your riou dir [here](https://github.com/jbwang1997/OBBDetection/blob/master/configs/obb/obb_iou_loss/README.md))
This [repo](https://github.com/lilanxiao/Rotated_IoU) helps if you have any idea for that.

**Comment by jbwang1997** [comment]
Yes, I have read this repo and attempt to add rotated IoU Loss in OBBDetection.

I am attempted to update it to a more general Poly IoU Loss, so that it can be used in the framework like Gliding Vertex.

**Comment by ming71** [comment]
Good job! :+1: BTW, there is no much overlap deviation between poly iou and riou. Maybe you can transform the polygon into obb, then calculate the riou loss between two obbs to replace the  Poly IoU Loss, it is more simple. 
Good luck!

**Comment by aeoles** [comment]
> Yes, I have read this repo and attempt to add rotated IoU Loss in OBBDetection.
> 
> I am attempted to update it to a more general Poly IoU Loss, so that it can be used in the framework like Gliding Vertex.

Hi , is there any progress for Poly IoU Loss?
