### ISSUE TITLE
hi，我发现新版本评估时候的gts数目不太对

### ISSUE THREAD

**Issue by HeuristicLU** [jbwang1997/OBBDetection#42]
hello，我一直在关注你这个模型，也在测试，之前用的是9月10号左右的版本进行测试，那个版本评估时候的gts是对的，但是最近更新了新版本后，发现同样的数据，新版本测试时候的gts个数和老版本不一样，我自己写了程序进行统计，发现新版本的gts数目不对，这块您这边有关注到么？
用新版本训练出来的模型，新版本评估map为76，老版本用这个模型评估的map为88。

**Comment by jbwang1997** [comment]
HRSC的dataset应该在之后没有发生过什么变化，可以再检查一下数据集的转化过程是否正确。
