### ISSUE TITLE
关于推理过程可视化的问题

### ISSUE THREAD

**Issue by RyanChanli** [jbwang1997/OBBDetection#46]
感谢您辛勤付出的工作！
在使用`python tools/test.py ${CONFIG_FILE} ${CHECKPOINT_FILE} [--out ${RESULT_FILE}] [--eval ${EVAL_METRICS}] [--show]`进行测试之后，在文件夹中所生成的图片是裁剪后的1024*1024的sub image而并非原始图片，另外所有的标注框均是绿色，想问下应该如何将图片重新拼接？并且将不同类别设置成不同颜色方便观察？

**Comment by jbwang1997** [comment]
通过增加--show只是可视化一次检测的结果，全图合并后的结果只能通过`python tools/test.py ${CONFIG_FILE} ${CHECKPOINT_FILE} --format-only --options save_dir=${SAVE_DIR}`得到最终结果后通过BboxToolkit中的visualize.py可视化。

如果要实现不同类别不同颜色，--show可以在[程序这里](https://github.com/jbwang1997/OBBDetection/blob/master/mmdet/models/detectors/obb/obb_base.py#L63)加入每一种类别的颜色。BboxToolkits/tools/visualize.py可以直接通过--colors加入。

**Comment by RyanChanli** [comment]
哦哦，感谢你的指导，谢谢author！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jbwang1997/OBBDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月11日(星期一) 晚上8:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jbwang1997/OBBDetection] 关于推理过程可视化的问题 (#46)





 
通过增加--show只是可视化一次检测的结果，全图合并后的结果只能通过python tools/test.py ${CONFIG_FILE} ${CHECKPOINT_FILE} --format-only --options save_dir=${SAVE_DIR}得到最终结果后通过BboxToolkit中的visualize.py可视化。
 
如果要实现不同类别不同颜色，--show可以在程序这里加入每一种类别的颜色。BboxToolkits/tools/visualize.py可以直接通过--colors加入。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by suisuinian-cloud** [comment]
Can't find /data1/nianian/OBBDetection-DOTA-smoothigiou_vis/s2anet_smoothigiou/P2736.txt, treated as empty txtfile
,why?
