### ISSUE TITLE
About the results on DOTA-v1.5

### ISSUE THREAD

**Issue by Richardych** [jbwang1997/OBBDetection#47]
Hi, 

Thanks for the great work, I wonder if you have done experiments on the DOTA-v1.5 which is a more challenging dataset.

Because our results with your Orient RCNN code on DOTA-v1.5 is only about 71% mAP.

**Comment by jbwang1997** [comment]
We don't test our model on DOTA-1.5. But the baseline results (Faster RCNN + RT) achieves 65.03% mAP as we refer in [AerialDetection model zoo](https://github.com/dingjiansw101/AerialDetection/blob/master/MODEL_ZOO.md). So I think 71% mAP is a pretty high performance if without augments.

**Comment by Richardych** [comment]
@jbwang1997 But I get the results with "configs/obb/oriented_rcnn/faster_rcnn_orpn_r50_fpn_1x_ms_rr_dota15.py" , which is multi-scale training with flip and rotation augments.

**Comment by jbwang1997** [comment]
The multi-scale training needs to split images under scales 1.5 and 0.5. This operation is completed by BboxToolkit. I wonder if your skip this operation.

Besides, The results in AerialDetection model zoo are trained on the DOTA train and val set. Check if you only train the model on train set.

**Comment by jbwang1997** [comment]
We have tested our method on DOTA-2.0 and the results are higher than Faster R-CNN+RT. So I think it's the same on DOTA-1.5.

**Comment by Richardych** [comment]
@jbwang1997 Can you tell us the results on DOTA-2.0 and the corresponding training and test config, Thanks.
