### ISSUE TITLE
请问HRSC数据集如何进行多尺度数据加强训练

### ISSUE THREAD

**Issue by Xinbo-01** [jbwang1997/OBBDetection#49]

**Comment by jbwang1997** [comment]
可以参考COCO多尺度训练的模型，在config的img_scales中多增加几个尺度，参考[config](https://github.com/jbwang1997/OBBDetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_caffe_fpn_mstrain_1x_coco.py#L14)

**Comment by Xinbo-01** [comment]
非常感谢您的回答，请问如何进行旋转图片，翻转等方式进行数据增强呢
