### ISSUE TITLE
model .pth

### ISSUE THREAD

**Issue by mmoghadam11** [jbwang1997/OBBDetection#5]
hi and thanx for your code 👍 
but if i want use it i have 2 way:

1. train your configs from scratch : it take much time to train each one even if i use colab it takes me out after one epoch ):
2. you give us the .pth checkpoint file : if you upload the checkpoint and log files it doesnt need we train it from first and we just need to test
+could you please upload  .pth and log file here or send it to me the link of them in google drive??
my second email is **mah.moghadam@mail.sbu.ac.ir**

**Comment by jbwang1997** [comment]
The models and logs will be uploaded right away. Now I am collecting and sorting models.

**Comment by mmoghadam11** [comment]
> The models and logs will be uploaded right away. Now I am collecting and sorting models.

where is `.pth` files for obb detections???

**Comment by jbwang1997** [comment]
> > The models and logs will be uploaded right away. Now I am collecting and sorting models.
> 
> where is `.pth` files for obb detections???

Hello, I recently uploaded the models of oriented rcnn. Please check [here](https://github.com/jbwang1997/OBBDetection/tree/master/configs/obb/oriented_rcnn) for details.
