### ISSUE TITLE
关于可视化结果的疑问

### ISSUE THREAD

**Issue by YeahHighly** [jbwang1997/OBBDetection#52]
您好，我调用了huge_image_demo.py对图片进行了预测，config文件obb/oriented_rcnn/faster_rcnn_orpn_r50_fpn_1x_dota10.py。但是我得到的可视化结果依然是水平框，请问这正常吗？是需要我自己去解析另外两个偏移量吗？
![Figure_1](https://user-images.githubusercontent.com/31301242/138043508-cfa9af05-5ab8-4d5f-857c-7bd4a4215f25.png)

**Comment by ReusJeffery** [comment]
> 您好，我调用了huge_image_demo.py对图片进行了预测，config文件obb/oriented_rcnn/faster_rcnn_orpn_r50_fpn_1x_dota10.py。但是我得到的可视化结果依然是水平框，请问这正常吗？是需要我自己去解析另外两个偏移量吗？ ![Figure_1](https://user-images.githubusercontent.com/31301242/138043508-cfa9af05-5ab8-4d5f-857c-7bd4a4215f25.png)

您好请问您解决了吗？我也遇到这样的情况
