### ISSUE TITLE
请问一下怎么评测模型性能。

### ISSUE THREAD

**Issue by lyccol** [jbwang1997/OBBDetection#6]
要怎么用test的来评测模型指数

**Comment by jbwang1997** [comment]
如果用dota数据集需要将检测结果提交到 [DOTA 验证通道](https://captain-whu.github.io/DOTA/evaluation.html)里。

OBBDetection可以直接生成 DOTA 的提交格式
···
python tools/test.py ${CONFIG_FILE} ${CHECKPOINT_FILE} --format-only --options save_dir=${SAVE_DIR}
···
将SAVE_DIR的输出压缩成 .zip 文件就可以直接提交了

**Comment by lyccol** [comment]
> 如果用dota数据集需要将检测结果提交到 [DOTA 验证通道](https://captain-whu.github.io/DOTA/evaluation.html)里。
> 
> OBBDetection可以直接生成 DOTA 的提交格式
> 
> ```
> python tools/test.py ${CONFIG_FILE} ${CHECKPOINT_FILE} --format-only --options save_dir=${SAVE_DIR}
> ```
> 
> 将SAVE_DIR的输出压缩成 .zip 文件就可以直接提交了

您好，我是用的自己的数据集，请问要如何评测自己的数据集呢？

**Comment by jbwang1997** [comment]
如果是自己的数据集可以在 [mmdet.datasets](https://github.com/jbwang1997/OBBDetection/tree/master/mmdet/datasets) 中创建自己的数据集的 dataset 并重写 evaluate 方法。这样在测试的时候通过增加 `--eval [MATRICS]` 可以直接进行测试。

dataset的写法可以参考 [custom.py](https://github.com/jbwang1997/OBBDetection/blob/master/mmdet/datasets/custom.py), [dior.py](https://github.com/jbwang1997/OBBDetection/blob/master/mmdet/datasets/obb/dior.py), [dota.py](https://github.com/jbwang1997/OBBDetection/blob/master/mmdet/datasets/obb/dota.py)。

如果已经得到结果可以调用 [arb_eval](https://github.com/jbwang1997/OBBDetection/blob/master/mmdet/core/evaluation/obb/obb_mean_ap.py#L173) 计算各个类别的mAP。arb_eval 函数的用法可以参考程序中的注释。

**Comment by lyccol** [comment]
谢谢 成功了，  我先直接修改了misc中DOTA数据集的类别为自定义的，然后修改了split_configs文件夹，并给test加上ann_dirs的值。

训练完毕后，

运行python tools/test.py configs/obb/faster_rcnn_obb/faster_rcnn_obb_r50_fpn_1x_dota10.py work_dirs/faster_rcnn_obb_r50_fpn_1x_dota10/latest.pth --out work_dirs/faster_rcnn_obb_r50_fpn_1x_dota10/res.pkl --eval mAP就成功了

**Comment by jimuIee** [comment]
你好，就是生成官方的提交文件test_pipeline应该怎么写呢，还是说直接复制train的pipeline就行了嘛

**Comment by demooooooo0303** [comment]
> 谢谢 成功了， 我先直接修改了misc中DOTA数据集的类别为自定义的，然后修改了split_configs文件夹，并给test加上ann_dirs的值。
> 
> 训练完毕后，
> 
> 运行python tools/test.py configs/obb/faster_rcnn_obb/faster_rcnn_obb_r50_fpn_1x_dota10.py work_dirs/faster_rcnn_obb_r50_fpn_1x_dota10/latest.pth --out work_dirs/faster_rcnn_obb_r50_fpn_1x_dota10/res.pkl --eval mAP就成功了

您好，可以指导一下吗？如何给test加上ann_dirs的值？

**Comment by demooooooo0303** [comment]
> 谢谢 成功了， 我先直接修改了misc中DOTA数据集的类别为自定义的，然后修改了split_configs文件夹，并给test加上ann_dirs的值。
> 
> 训练完毕后，
> 
> 运行python tools/test.py configs/obb/faster_rcnn_obb/faster_rcnn_obb_r50_fpn_1x_dota10.py work_dirs/faster_rcnn_obb_r50_fpn_1x_dota10/latest.pth --out work_dirs/faster_rcnn_obb_r50_fpn_1x_dota10/res.pkl --eval mAP就成功了

请问一下，这里的work_dirs/faster_rcnn_obb_r50_fpn_1x_dota10/latest.pth --out work_dirs/faster_rcnn_obb_r50_fpn_1x_dota10/res.pkl  PKL文件是如何生成的？
