### ISSUE TITLE
About the result

### ISSUE THREAD

**Issue by Banhkun** [jbwang1997/OBBDetection#63]
![image](https://user-images.githubusercontent.com/83081141/139538639-4e20bb37-9fa9-4b68-b017-24710bf49e0a.png)
Thanks for your contribution!
Is this the result of the model on VOC 2007 and 2012 ?
I wonder because you write "HRSC dataset" above

**Comment by jbwang1997** [comment]
The voc07 and voc12 donate different metrics. The models are trained on the HRSC dataset and evaluated in voc07 and voc12 metrics separately.

**Comment by Banhkun** [comment]
> The voc07 and voc12 donate different metrics. The models are trained on the HRSC dataset and evaluated in voc07 and voc12 metrics separately.
Thank you

**Comment by Banhkun** [comment]
Thank you

**Comment by Banhkun** [comment]
Can you help me the last thing? 
How can I evaluate in voc07 and voc12 metrics separately?.
Cause the test script only have 2 options for eval metrics: **mAP** and **recall**. I don't know that mmdetection support it.
![image](https://user-images.githubusercontent.com/83081141/139592679-02c87b2c-c308-4988-a372-b88f8ac12b59.png)
Thank you

**Comment by jbwang1997** [comment]
You can add `--options use_07_metric=False` at the end of your command to change the metric from voc07 to voc12.

**Comment by Banhkun** [comment]
Oh! Thanks
