### ISSUE TITLE
DOTA数据集测试mAP为0

### ISSUE THREAD

**Issue by volcanolee4** [jbwang1997/OBBDetection#65]
您好！首先感谢您的杰出工作！
我使用您提供的faster_rcnn_orpn_r50_fpn_1x_mssplit_rr_dota10_epoch12.pth参数在DOTA1.0上进行了多GPU测试，测试指令如下：
![image](https://user-images.githubusercontent.com/93360352/140448156-c34a5142-0720-4f73-b160-a1c938c1b951.png)
测试成功完成后却得到了这样的结果：
![image](https://user-images.githubusercontent.com/93360352/140448286-7d45d264-58fb-47a2-81c5-a6e239fac05d.png)
这可能是什么原因导致的呢？

**Comment by jbwang1997** [comment]
test上的结果需要提交到DOTA官网上进行测试，本地没有label所有测试结果都是0，生成的提交文件就在save_dir中

**Comment by volcanolee4** [comment]
好的 感谢！
