### ISSUE TITLE
Interface of eight-params method

### ISSUE THREAD

**Issue by tymanman** [jbwang1997/OBBDetection#66]
Hi,Can I use the code to preform eight-params based method directly?

**Comment by jbwang1997** [comment]
Yes, this toolkit support 'poly' bboxes which is eight-params, you can refer to `gliding vertex` for details.

**Comment by tymanman** [comment]
Thank u.But I mean that I wanna make the network predict 8 params(four points) directly instead of gliding vertex.So,is there a solution in this codebase?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jbwang1997/OBBDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月8日(星期一) 晚上6:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jbwang1997/OBBDetection] Interface of eight-params method (Issue #66)





 
Yes, this toolkit support 'poly' bboxes which is eight-params, you can refer to gliding vertex for details.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jbwang1997** [comment]
Oh, currently there is no model directly predicting the 4 points. You need to build it by yourself.

OBBDetection already supports the necessary operations for 4 point polygon, like NMS and IoU calculator.
