### ISSUE TITLE
在windows下安装，出现sigmoid_focal_loss_cuda.obj : error LNK2001: 无法解析的外部符号 "public: long __cdecl at::Tensor::item<long>(void)const " (??$item@J@Tensor@at@@QEBAJXZ)错误

### ISSUE THREAD

**Issue by JinqingZhengTju** [jbwang1997/OBBDetection#69]
在windows下安装，出现sigmoid_focal_loss_cuda.obj : error LNK2001: 无法解析的外部符号 "public: long __cdecl at::Tensor::item<long>(void)const " (??$item@J@Tensor@at@@QEBAJXZ)错误，是不是所依赖的mmdetectionV2.2的安装不兼容windows，按照网上去修改sigmoid_focal_loss_cuda.cu也未能解决问题。我的cuda版本是V11.3，pytorch版本是1.10.0。不知道有没有同学遇到这个问题？该项目是不是只兼容Ubuntu呢？

**Comment by jbwang1997** [comment]
早期MMDetection没有进行windows适配，可以会出现问题

**Comment by JinqingZhengTju** [comment]
谢谢。我再试下在ubuntu上去配置。最新的MMDetectionV2.18在windows下是可以配置成功的。

**Comment by 137xiaoyu** [comment]
同遇到，3090 + Windows，试过如下配置都没成功：
CUDA 11.1 + torch 1.8.0
CUDA 11.3 + torch 1.10.0

mmcv-full等安装都没有问题
