### ISSUE TITLE
环境安装报错

### ISSUE THREAD

**Issue by xumengen** [jbwang1997/OBBDetection#7]
step d中的pip install -v -e . 报错
![image](https://user-images.githubusercontent.com/38242124/130412066-7228f478-93e4-4e56-b35d-eba5897275b0.png)
![image](https://user-images.githubusercontent.com/38242124/130412084-97271e78-06f7-4de1-afc9-27cd87c212d6.png)
![image](https://user-images.githubusercontent.com/38242124/130412096-f73180ac-7443-4e5e-b3cd-20cae98e08aa.png)

torch 版本1.7.0 cudatoolkit版本11.0 NVIDIA GeForce RTX 3090

**Comment by jbwang1997** [comment]
这个应该还是环境的问题，能否看一下你环境配置

**Comment by xumengen** [comment]
> 这个应该还是环境的问题，能否看一下你环境配置

![image](https://user-images.githubusercontent.com/38242124/130422194-eadae6c4-643d-4239-b03f-94bd8f3a5189.png)
![image](https://user-images.githubusercontent.com/38242124/130422216-74340c0c-3c7d-4512-b40c-4af519d7b66c.png)

这是conda环境，我感觉是我torch版本的问题，但我也试了torch 1.5，也会报错

**Comment by jbwang1997** [comment]
你的CUDA是直接安装在默认路径下的吗，还是设置了CUDA_HOME。

可以通过nvcc --version查看一下电脑上安装的CUDA版本，是否和cudatoolkit的版本一样。

**Comment by lyccol** [comment]
你可能需要pytorch 1.3.1，我装高版本也会报这个错

**Comment by xumengen** [comment]
> 你的CUDA是直接安装在默认路径下的吗，还是设置了CUDA_HOME。
> 
> 可以通过nvcc --version查看一下电脑上安装的CUDA版本，是否和cudatoolkit的版本一样。



> 你的CUDA是直接安装在默认路径下的吗，还是设置了CUDA_HOME。
> 
> 可以通过nvcc --version查看一下电脑上安装的CUDA版本，是否和cudatoolkit的版本一样。

设置了CUDA的路径的，和cudatoolkit版本是一致的

**Comment by xumengen** [comment]
> 你可能需要pytorch 1.3.1，我装高版本也会报这个错

那你的cudatoolkit是啥版本的哦

**Comment by xumengen** [comment]
> 我的是
> NVIDIA-SMI 410.48 Driver Version: 410.48
> 4*2080ti
> 
> # nvcc -V
> Command 'nvcc' not found, but can be installed with:
> apt install nvidia-cuda-toolkit
> 
> # cat /usr/local/cuda/version.txt
> CUDA Version 10.2.89

ok，我用的3090的卡，3090貌似只能用cuda11

**Comment by lyccol** [comment]
> > 我的是
> > NVIDIA-SMI 410.48 Driver Version: 410.48
> > 4*2080ti
> > # nvcc -V
> > Command 'nvcc' not found, but can be installed with:
> > apt install nvidia-cuda-toolkit
> > # cat /usr/local/cuda/version.txt
> > CUDA Version 10.2.89
> 
> ok，我用的3090的卡，3090貌似只能用cuda11

建议你可以尝试一下这个，可以使用cuda11.0。
https://github.com/csuhan/ReDet/issues/1

**Comment by jbwang1997** [comment]
我在3090上使用CUDA 10.2.89编译成功过，pytorch1.9.0。你可以试一下换成pytorch1.9.0。

**Comment by jbwang1997** [comment]
> > > 我的是
> > > NVIDIA-SMI 410.48 Driver Version: 410.48
> > > 4*2080ti
> > > # nvcc -V
> > > Command 'nvcc' not found, but can be installed with:
> > > apt install nvidia-cuda-toolkit
> > > # cat /usr/local/cuda/version.txt
> > > CUDA Version 10.2.89
> > 
> > 
> > ok，我用的3090的卡，3090貌似只能用cuda11
> 
> 建议你可以尝试一下这个方法，可以使用cuda11.0。
> [csuhan/ReDet#1](https://github.com/csuhan/ReDet/issues/1)

应该不是这个问题，OBBDetection用的是mmdetection2.2，在v2版本的mmdetection已经将这个改过了。

**Comment by xumengen** [comment]
> > > > 我的是
> > > > NVIDIA-SMI 410.48 Driver Version: 410.48
> > > > 4*2080ti
> > > > # nvcc -V
> > > > Command 'nvcc' not found, but can be installed with:
> > > > apt install nvidia-cuda-toolkit
> > > > # cat /usr/local/cuda/version.txt
> > > > CUDA Version 10.2.89
> > > 
> > > 
> > > ok，我用的3090的卡，3090貌似只能用cuda11
> > 
> > 
> > 建议你可以尝试一下这个方法，可以使用cuda11.0。
> > [csuhan/ReDet#1](https://github.com/csuhan/ReDet/issues/1)
> 
> 应该不是这个问题，OBBDetection用的是mmdetection2.2，在v2版本的mmdetection已经将这个改过了。

我在3090上重新试了torch1.7.1和cuda11.0，可以训练了

**Comment by houw0517** [comment]
> > > > > 我的是
> > > > > NVIDIA-SMI 410.48 Driver Version: 410.48
> > > > > 4*2080ti
> > > > > # nvcc -V
> > > > > Command 'nvcc' not found, but can be installed with:
> > > > > apt install nvidia-cuda-toolkit
> > > > > # cat /usr/local/cuda/version.txt
> > > > > CUDA Version 10.2.89
> > > > 
> > > > 
> > > > ok，我用的3090的卡，3090貌似只能用cuda11
> > > 
> > > 
> > > 建议你可以尝试一下这个方法，可以使用cuda11.0。
> > > [csuhan/ReDet#1](https://github.com/csuhan/ReDet/issues/1)
> > 
> > 
> > 应该不是这个问题，OBBDetection用的是mmdetection2.2，在v2版本的mmdetection已经将这个改过了。
> 
> 我在3090上重新试了torch1.7.1和cuda11.0，可以训练了

您好 可以私信交流一下吗  我的环境也是3090   现在还有问题

**Comment by houw0517** [comment]
> 你的CUDA是直接安装在默认路径下的吗，还是设置了CUDA_HOME。
> 
> 可以通过nvcc --version查看一下电脑上安装的CUDA版本，是否和cudatoolkit的版本一样。

请问 cuda版本和cudatoolkit的版本一样  怎么解决

**Comment by houw0517** [comment]
> 你的CUDA是直接安装在默认路径下的吗，还是设置了CUDA_HOME。
> 
> 可以通过nvcc --version查看一下电脑上安装的CUDA版本，是否和cudatoolkit的版本一样。

请问 cuda版本和cudatoolkit版本不一样 怎么办？
