### ISSUE TITLE
Poly IoU Loss

### ISSUE THREAD

**Issue by chandlerbing65nm** [jbwang1997/OBBDetection#76]
Did you try to implement [Poly IoU Loss](https://github.com/jbwang1997/OBBDetection/tree/master/configs/obb/poly_iou_loss) in [RoI Transformer](https://github.com/jbwang1997/OBBDetection/tree/master/configs/obb/roi_transformer) and [Faster-RCNN OBB](https://github.com/jbwang1997/OBBDetection/tree/master/configs/obb/faster_rcnn_obb)? 

Will it work if I tried to? I have not read the paper about it yet. Thanks!

**Comment by jbwang1997** [comment]
Yes, I have tried to implement PolyIoULoss in the second stage of Faster RCNN OBB. But the results are not good. 

The Roi Transformer is not yet.

**Comment by chandlerbing65nm** [comment]
> [Poly IoU Loss](https://github.com/jbwang1997/OBBDetection/tree/master/configs/obb/poly_iou_loss)

Which of the two is better when you implement, [GIoU ](https://github.com/jbwang1997/OBBDetection/blob/master/configs/obb/poly_iou_loss/retinanet_obb_r50_fpn_giouloss_1x_dota.py) or the [IoU](https://github.com/jbwang1997/OBBDetection/blob/master/configs/obb/poly_iou_loss/retinanet_obb_r50_fpn_iouloss_1x_dota.py) ?

**Comment by jbwang1997** [comment]
As shown in experiments, they don't have large differences.

**Comment by chandlerbing65nm** [comment]
@jbwang1997 how about in [Oriented RCNN](https://github.com/chandlerbing65nm/OBBDetection/tree/master/configs/obb/oriented_rcnn)? have you tried implementing IoU Loss?
