### ISSUE TITLE
AttributeError: module 'BboxToolkit.datasets' has no attribute 'load_dota1.5'

### ISSUE THREAD

**Issue by chentao2016** [jbwang1997/OBBDetection#78]
When I run: python img_split.py --base_json split_configs/dota1_5/ms_train.json

The error occurs:
Loading original data!!!
Traceback (most recent call last):
  File "img_split.py", line 309, in <module>
    main()
  File "img_split.py", line 256, in main
    load_func = getattr(bt.datasets, 'load_'+args.load_type)
AttributeError: module 'BboxToolkit.datasets' has no attribute 'load_dota1.5'

Could you give me some suggestions to solve this error?

**Comment by jbwang1997** [comment]
Hi, I find this is a bug in split_configs, I have fixed this bug in the least commit. You can update BboxToolkit or change split_config according the new commit.
