### ISSUE TITLE
dist_test error

### ISSUE THREAD

**Issue by zzndream** [jbwang1997/OBBDetection#79]
我测试了dota1.0 和HRSC数据集，在使用多个GPU，用dist_test.py eval时，都会出现以下错误：
  File "/home/workspaces/pycharm/OBBDetection/mmdet/models/dense_heads/anchor_head.py", line 566, in get_bboxes                  │········
    img_shape = img_metas[img_id]['img_shape']                                                                                   │········
TypeError: 'DataContainer' object is not subscriptable

**Comment by jbwang1997** [comment]
这可能是因为pytorch版本的问题，可以尝试更改pytorch版本
