### ISSUE TITLE
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by wtl2001** [jbwang1997/OBBDetection#8]
Traceback (most recent call last):
  File "tools/test.py", line 153, in <module>
    main()
  File "tools/test.py", line 147, in main
    dataset.format_results(outputs, **kwargs)
  File "/root/wtl2/OBBDetection/mmdet/datasets/obb/dota.py", line 123, in format_results
    bboxes, scores = dets[:, :-1], dets[:, [-1]]
dets的shape是(6,)，我怀疑是dets.shape的问题

**Comment by chandlerbing65nm** [comment]
I still have this issue even with the latest commit. How to actually solve this?

**Comment by jbwang1997** [comment]
Can you provide more information on this bug? @chandlerbing65nm

**Comment by chandlerbing65nm** [comment]
> Can you provide more information on this bug? @chandlerbing65nm

@jbwang1997 When I run this 
```
python tools/test.py configs/obb/oriented_rcnn/orpn_r50_fpn_1x_dota10.py work_dirs/orpn_r50_fpn_1x_dota10/epoch_12.pth --format-only --options save_dir=work_dirs/orpn_r50_fpn_1x_dota10/task1
```

An error occurs: 
```
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

This is directed to this code [line](https://github.com/jbwang1997/OBBDetection/blob/86fb098d8d2ff3fc3cc447714d89a44c0939614a/mmdet/datasets/obb/dota.py#L124).

**Comment by jbwang1997** [comment]
Oh, The orpn_r50_fpn_1x_dota10.py only contains RPN and generates proposals. Its output is not the format of prediction boxes. Thus this error occurred.

**Comment by chandlerbing65nm** [comment]
> Oh, The orpn_r50_fpn_1x_dota10.py only contains RPN and generates proposals. Its output is not the format of prediction boxes. Thus this error occurred.

How can I run a test for submission in dota server? @jbwang1997

**Comment by jbwang1997** [comment]
Yes,  faster_rcnn_orpn_r50_fpn_1x_dota10.py is the full orietned rcnn config. We also have provided the .pth files in oriented rcnn readme.md. @chandlerbing65nm

**Comment by chandlerbing65nm** [comment]
> Yes, faster_rcnn_orpn_r50_fpn_1x_dota10.py is the full orietned rcnn config. We also have provided the .pth files in oriented rcnn readme.md. @chandlerbing65nm

Question, can I run testing in [3, 512, 512] img scale on your checkpoint files trained in [3, 1024, 1024]?

**Comment by jbwang1997** [comment]
> > Yes, faster_rcnn_orpn_r50_fpn_1x_dota10.py is the full orietned rcnn config. We also have provided the .pth files in oriented rcnn readme.md. @chandlerbing65nm
> 
> Question, can I run testing in [3, 512, 512] img scale on your checkpoint files trained in [3, 1024, 1024]?

I think the testing scale should be the same as training. Otherwise, the mAP will drop.

**Comment by jimuIee** [comment]
你好，请问是怎么改的
