### ISSUE TITLE
运行 tool/test.py 出现IndexError

### ISSUE THREAD

**Issue by ZhouHuang23** [jbwang1997/OBBDetection#82]
作者您好！

我正常训练DOTA1.0数据后，在运行：

python test/tools.py config/obb/oriented_rcnn/faster_rcnn_orpn_r101_1x_data10.py work_dirs/faster_rcnn_orpn_r101_1x_data10/latest.pth --show-dir 

出现以下Bug：

在 File " / 00D / 0bbdetection / Bboxtoolkit / Bboxtoolkit / visualization / show . py " , line 70 , in < Listcomp > bboxes=[ boxes [ labels == i ] for i in range ( labels . max() ) + 1 ) ] 
出现：

Indexerror : boolean index did not match indexed array along dimension 0 ; dimension is 9 but corresponding boolean dimension is 17

只修改了配置路径，其它未做修改。

**Comment by jbwang1997** [comment]
可能是最近BboxToolkit的接口发生变化过，OBBDetection在不久前才改过来。

建议将OBBDetection与BboxToolkit从新更新一下

**Comment by ZhouHuang23** [comment]
您好，我重新clone了最新的OBBDetection与BboxToolkit，并python test/tools.py ...... 
但仍然出现了同样的Bug，麻烦您再处理一下。

**Comment by jbwang1997** [comment]
确实有bug，在最新的commit我已经进行了修改

**Comment by ZhouHuang23** [comment]
谢谢修复bug！
