### ISSUE TITLE
请问results中的aligned_fields有什么用？

### ISSUE THREAD

**Issue by 137xiaoyu** [jbwang1997/OBBDetection#88]
`mmdet/datasets/pipelines/obb/base.py`和`mmdet/datasets/pipelines/obb/dota.py`中有对`results['aligned_fields']`做出修改，但我没有找到其他代码调用该键值

我采用了新版mmdet的`RandomCrop`，其中`allow_negative_crop`这一项会导致`results['aligned_fields']`的ignore出现问题，我想知道该键值是否重要，如果不重要我可以暂时忽略它

**Comment by jbwang1997** [comment]
aligned_fields是目标的一些信息比如diffs, truncs。这些信息的长度要与目标数量保持一致，所有把它们收集到一起。一般是用不上的，可以忽略掉。

**Comment by 137xiaoyu** [comment]
> aligned_fields是目标的一些信息比如diffs, truncs。这些信息的长度要与目标数量保持一致，所有把它们收集到一起。一般是用不上的，可以忽略掉。

感谢！
