### ISSUE TITLE
Onnx Conversion Error

### ISSUE THREAD

**Issue by selimceylan** [jbwang1997/OBBDetection#94]
**Describe the bug**
Hi, I am trying to convert my pth file to onnx file using tools/pytorch2onnx.py. Unfortunately, it does not work.

**Reproduction**
1. What command or script did you run?
```
python tools/pytorch2onnx.py /home/gi-admin2/Dev/OBBDetection/configs/obb/oriented_rcnn/faster_rcnn_orpn_r50_fpn_1x_ms_rr_dota10.py /home/Dev/OBBDetection/work-dir/latest.pth --out /home/Dev/OBBDetection/work-dir/latest.onnx
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
No.
3. What dataset did you use?
I used the dataset DOTA-v1.0 in https://captain-whu.github.io/DOTA/dataset.html
Also I tried this with default pth file which faster_rcnn_orpn_r50_fpn_1x_dota10_epoch12.pth in https://drive.google.com/file/d/1Rv5sctUcnEDSGZhMxgXVZ-7dMai0qrIr/view
**Environment**
I took this message:
ModuleNotFoundError: No module named 'mmcv'   
but mmcv-full=1.3.9 already installed.

**Error traceback**
If applicable, paste the error trackback here.
```

  File "/home/Dev/OBB3/OBBDetection/mmdet/ops/roi_align_rotated/roi_align_rotated.py", line 29, in forward
    features, rois, spatial_scale, out_h, out_w, sample_num, aligned)
RuntimeError: roi_width >= 0 && roi_height >= 0INTERNAL ASSERT FAILED at "mmdet/ops/roi_align_rotated/src/roi_align_rotated_cpu.cpp":237, please report a bug to PyTorch. ROIs in ROIAlignRotated do not have non-negative size!
```

**Comment by jbwang1997** [comment]
Sorry, I don't know much about ONNX, thus I haven't debugged the ONNX relating functions.

**Comment by selimceylan** [comment]
Thanks for replying. If you are going to do something about ONNX in future, please let me know.
